CREATE DATABASE SQLQuery3;
USE SQLQUERY3;

CREATE TABLE PRODUCT_MANUFACTURERS(MANUFACTURER_ID INT PRIMARY KEY,
BUSINESS_NAME CHARACTER(50));

INSERT INTO PRODUCT_MANUFACTURERS(MANUFACTURER_ID,BUSINESS_NAME)
VALUES (91,'THE PEN MAKERS INC.'),
(92,'THE ERASER MAKERS INC.'),
(93,'THE NOTEBOOK MAKERS INC.');

SELECT*FROM PRODUCT_MANUFACTURERS;

CREATE TABLE PRODUCT_NAMES(
PRODUCT_NAME_ID INT,
PRODUCT_NAME CHARACTER(50),
MANUFACTURER_ID INT FOREIGN KEY REFERENCES
PRODUCT_MANUFACTURERS(MANUFACTURER_ID));
/*In this table we have set a dependence between tables with the command foreign key references*/

INSERT INTO PRODUCT_NAMES VALUES (1001,'X PEN',91),(1002,'Y Eraser',92),(1003,'Z Notebook',93);
SELECT*FROM PRODUCT_NAMES;

/*

How many tables do we have in this database?
2
How many entities do we have in this database?
2
What is the name of our database?
SQLQuery3
How many records do we have on each table?
PRODUCT_MANUFACTURERS:3
PRODUCT_NAMES:3
*/

